app = "hades-kang"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
    builder = "heroko/buildpacks:latest"

[env]
    SUDO_USERS = 5754821527
    BOT_TOKEN = 5620689794:AAHIXnj26d8JvmT8G37oandkoBVNnOVJODU

[experimental]
    allowed_public_ports = []
    auto_rollback = true
